views.filter.annotation_field_filter:
  type: views.filter.in_operator
  label: 'Annotation field filter'

views.filter.annotation_type_filter:
  type: views.filter.in_operator
  label: 'Annotation type filter'

views.filter.annotation_target_filter:
  type: views.filter.in_operator
  label: 'Annotation target filter'
